"""Render an agent trace as a human-readable markdown report."""

from __future__ import annotations

import json
from pathlib import Path
from textwrap import indent

from omnilab.agent import AgentTrace, Step


def _summarize_tool_call(s: Step) -> str:
    args = s.args or {}
    arg_str = ", ".join(f"{k}={json.dumps(v)[:80]}" for k, v in args.items())
    return f"`{s.name}({arg_str})`"


def render_markdown(trace: AgentTrace) -> str:
    lines: list[str] = []
    lines.append(f"# OmniLab Report")
    lines.append("")
    lines.append(f"**Question:** {trace.question}")
    lines.append("")
    lines.append(f"**Model:** `{trace.model_used}` via Vertex AI")
    lines.append(f"**Started:** {trace.started_at.isoformat()}Z")
    lines.append(f"**Steps:** {len(trace.steps)}")
    tool_calls = [s for s in trace.steps if s.kind == "tool_call"]
    total_tool_time = sum(
        s.seconds for s in trace.steps if s.kind == "tool_result"
    )
    lines.append(f"**Skills invoked:** {len(tool_calls)} call(s), ~{total_tool_time:.1f}s of tool execution")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Final Answer")
    lines.append("")
    lines.append(trace.final_answer or "_(no final answer produced)_")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Execution Trace")
    lines.append("")
    for i, s in enumerate(trace.steps, 1):
        if s.kind == "plan":
            lines.append(f"### Step {i} — Plan")
            lines.append("")
            lines.append("> " + (s.text or "").replace("\n", "\n> "))
            lines.append("")
        elif s.kind == "tool_call":
            lines.append(f"### Step {i} — Skill call: {_summarize_tool_call(s)}")
            lines.append("")
        elif s.kind == "tool_result":
            preview = (s.text or "")[:1200]
            lines.append(f"<details><summary>Result from `{s.name}` ({s.seconds:.1f}s, {len(s.text or '')} chars)</summary>")
            lines.append("")
            lines.append("```json")
            lines.append(preview)
            if s.text and len(s.text) > len(preview):
                lines.append(f"... [truncated, {len(s.text) - len(preview)} more chars]")
            lines.append("```")
            lines.append("")
            lines.append("</details>")
            lines.append("")
        elif s.kind == "final":
            pass  # already shown above
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("_Generated by OmniLab — GDM Science Skills × Gemini agent harness._")
    return "\n".join(lines)


def save_markdown(trace: AgentTrace, path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_markdown(trace))
    return path
